baseURL = "https://www.csshole.com"
languageCode = "en-us"
title = "CSS Hole - Interactive Web Apps using only HTML and CSS"
theme = ""
googleAnalytics = ""

[params]
    author = "csshole"
    description = "Sudoku Farm"
    githubUsername = "csshole"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    favicon = "/images/circle_logo.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/sudoku/"
    name = "Sudoku"
    weight = 2

[[menu.main]]
    url = "/maps/"
    name = "Maps"
    weight = 3

[[menu.main]]
    url = "/math/"
    name = "Math"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5
